import http from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {randomBytes,timingSafeEqual} from 'node:crypto';
const dir=process.env.DATA_DIR ? new URL('file://'+process.env.DATA_DIR.replace(/\/$/,'')+'/') : new URL('./.data/',import.meta.url); await mkdir(dir,{recursive:true});
const file=new URL('board.json',dir); let state;
try{state=JSON.parse(await readFile(file,'utf8'))}catch(e){if(e.code!=='ENOENT')throw e;state={"items": [{"id": "chatgpt", "title": "ChatGPT", "content": "\u25ce", "x": 485, "y": 200, "cluster": "AI systems", "kind": "note", "name": "Not recorded", "date": "Not recorded", "reason": "From the physical board. Original contributor and context have not been entered yet."}, {"id": "claude", "title": "Claude", "content": "\u2733", "x": 435, "y": 335, "cluster": "AI systems", "kind": "note", "name": "Not recorded", "date": "Not recorded", "reason": "From the physical board. Original contributor and context have not been entered yet."}, {"id": "hal", "title": "HAL 9000", "content": "HAL 9000\n\ud83d\udd34", "x": 700, "y": 440, "cluster": "AI systems", "kind": "note", "name": "Not recorded", "date": "Not recorded", "reason": "From the physical board. Original contributor and context have not been entered yet."}, {"id": "gemini", "title": "Gemini", "content": "\u2726", "x": 925, "y": 460, "cluster": "AI systems", "kind": "note", "name": "Not recorded", "date": "Not recorded", "reason": "From the physical board. Original contributor and context have not been entered yet."}, {"id": "clippy", "title": "Clippy", "content": "\ud83d\udcce", "x": 480, "y": 530, "cluster": "Assistants", "kind": "note", "name": "Not recorded", "date": "Not recorded", "reason": "From the physical board. Original contributor and context have not been entered yet."}, {"id": "surveillance", "title": "Watching & being watched", "content": "\u25c9", "x": 1140, "y": 585, "cluster": "Surveillance", "kind": "note", "name": "Not recorded", "date": "Not recorded", "reason": "From the physical board. Original contributor and context have not been entered yet."}, {"id": "question", "title": "A thought from the board", "content": "I have no \u2026 and I must \u2026", "x": 175, "y": 495, "cluster": "Questions", "kind": "note", "name": "Not recorded", "date": "Not recorded", "reason": "From the physical board. Original contributor and context have not been entered yet."}, {"id": "belief", "title": "I want to believe", "content": "AI WANT TO BELIEVE", "x": 135, "y": 190, "cluster": "Questions", "kind": "note", "name": "Not recorded", "date": "Not recorded", "reason": "From the physical board. Original contributor and context have not been entered yet."}], "connections": [["chatgpt", "hal"], ["claude", "hal"], ["hal", "gemini"], ["hal", "clippy"], ["hal", "surveillance"], ["question", "hal"]], "pending": []};await writeFile(file,JSON.stringify(state));}
const sessions=new Set();const save=()=>writeFile(file,JSON.stringify(state));let mutation=Promise.resolve();
function authorized(req){return sessions.has(req.headers.authorization?.replace('Bearer ',''))}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(data))}
async function body(req){let s='';for await(const c of req){s+=c;if(s.length>7_000_000)throw Error('Submission too large')}return JSON.parse(s||'{}')}
const text=(v,max)=>typeof v==='string'?v.trim().slice(0,max):'';
const server=http.createServer(async(req,res)=>{try{
const path=new URL(req.url,'http://localhost').pathname;
if(path==='/api/board'&&req.method==='GET')return json(res,200,{items:state.items,connections:state.connections});
if(path==='/api/login'&&req.method==='POST'){const {password}=await body(req);const configured=process.env.ADMIN_PASSWORD;if(!configured)return json(res,503,{error:'Set ADMIN_PASSWORD on the server to enable teacher access.'});const a=Buffer.from(String(password)),b=Buffer.from(configured);if(a.length!==b.length||!timingSafeEqual(a,b))return json(res,401,{error:'Incorrect password'});const token=randomBytes(32).toString('hex');sessions.add(token);setTimeout(()=>sessions.delete(token),3600000).unref();return json(res,200,{token})}
if(path==='/api/submissions'&&req.method==='POST'){const b=await body(req);const item={id:randomBytes(12).toString('hex'),title:text(b.title,120),name:text(b.name,80),reason:text(b.reason,2000),kind:b.kind,content:text(b.content,6_000_000),x:Math.max(100,Math.min(1300,Number(b.x)||650)),y:Math.max(100,Math.min(850,Number(b.y)||450)),date:new Date().toISOString().slice(0,10),cluster:text(b.cluster,80),links:Array.isArray(b.links)?b.links.filter(id=>state.items.some(i=>i.id===id)).slice(0,20):[]};if(!item.title||!item.name||!item.reason||!item.content||!['note','link','image'].includes(item.kind))return json(res,400,{error:'Complete the title, name, context and content.'});if(item.kind==='link'&&!/^https?:\/\//i.test(item.content))return json(res,400,{error:'Use an http or https link.'});if(item.kind==='image'&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(item.content))return json(res,400,{error:'Use a PNG, JPEG or WebP image.'});mutation=mutation.then(async()=>{state.pending.push(item);await save()});await mutation;return json(res,201,{ok:true})}
if(path.startsWith('/api/teacher')){if(!authorized(req))return json(res,401,{error:'Teacher sign-in required'});if(req.method==='GET')return json(res,200,state.pending);if(req.method==='POST'){const b=await body(req);const index=state.pending.findIndex(i=>i.id===b.id);if(index<0)return json(res,404,{error:'Submission no longer exists'});if(!['approve','reject'].includes(b.action))return json(res,400,{error:'Invalid action'});mutation=mutation.then(async()=>{const i=state.pending.findIndex(i=>i.id===b.id);if(i<0)return;const [item]=state.pending.splice(i,1);if(b.action==='approve'){item.title=text(b.title,120)||item.title;item.reason=text(b.reason,2000)||item.reason;state.items.push(item);state.connections.push(...item.links.map(id=>[item.id,id]));delete item.links}await save()});await mutation;return json(res,200,{ok:true})}}
const files={'/':'index.html','/app.js':'app.js','/style.css':'style.css'};if(req.method!=='GET'||!files[path])return json(res,404,{error:'Not found'});const data=await readFile(new URL('./public/'+files[path],import.meta.url));res.writeHead(200,{'Content-Type':path.endsWith('.js')?'text/javascript':path.endsWith('.css')?'text/css':'text/html','X-Content-Type-Options':'nosniff'});res.end(data);
}catch(e){json(res,400,{error:e.message})}});
server.listen(Number(process.env.PORT)||3000,'0.0.0.0',()=>console.log('Redstring listening on port '+(process.env.PORT||3000)));
