import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {readFile} from 'node:fs/promises';
import {validateSubmission,mergeBoard,validContent} from './public/model.js';
const item={id:'student',title:'New idea',name:'A student',reason:'Connects to AI',kind:'note',content:'A question',cluster:'AI systems',date:'2026-10-06',links:['hal'],x:500,y:400};
test('submission validation rejects unsafe links and oversized content',()=>{
 assert.equal(validateSubmission(item),item);
 for(const content of ['javascript:alert(1)','data:text/html,test','https://user:password@example.com'])assert.equal(validContent('link',content),false);
 assert.equal(validContent('link','https://example.com'),true);
 assert.throws(()=>validateSubmission({...item,name:''}));
 assert.throws(()=>validateSubmission({...item,content:'a'.repeat(4001)}));
 assert.throws(()=>validateSubmission({...item,x:NaN}));
 assert.throws(()=>validateSubmission({...item,links:Array(21).fill('hal')}));
 assert.equal(validContent('image','data:image/svg+xml;base64,AAAA'),false);
});
test('published contributions merge with seed and add valid connections',async()=>{
 const seed=JSON.parse(await readFile(new URL('./public/board.json',import.meta.url)));
 const merged=mergeBoard(seed,[item]);assert.equal(merged.items.length,seed.items.length+1);assert.ok(merged.connections.some(pair=>pair.includes('student')&&pair.includes('hal')));
 const edited=mergeBoard(seed,[{...item,id:'hal',title:'Updated HAL',links:[]}]);assert.equal(edited.items.length,seed.items.length);assert.equal(edited.items.find(i=>i.id==='hal').title,'Updated HAL');
});
test('GitHub Pages subpath serves the board with relative assets and no API',async()=>{
 const child=spawn(process.execPath,['server.js'],{env:{...process.env,PORT:'3198'}});
 try{await new Promise((resolve,reject)=>{child.stdout.once('data',resolve);child.once('error',reject);child.once('exit',()=>reject(Error('Server exited early')))});
 const base='http://localhost:3198/redstring/';const page=await fetch(base);assert.equal(page.status,200);const html=await page.text();assert.match(html,/href="\.\/style\.css(?:\?[^"]*)?"/);assert.match(html,/src="\.\/app\.js(?:\?[^"]*)?"/);
 for(const file of ['app.js','app.js?v=20261010-3','firebase.js','firebase-config.js','model.js','style.css','style.css?v=20261010-3','board.json'])assert.equal((await fetch(base+file)).status,200,file);
 assert.ok(!html.includes('id="teacher"'));const editorAlias=await fetch(base+'editor');assert.equal(editorAlias.status,200);assert.ok((await editorAlias.text()).includes('../editor.html'));const board=await (await fetch(base+'board.json')).json();assert.equal(board.items.length,8);
 const app=await (await fetch(base+'app.js')).text();assert.ok(!app.includes('/api/'));
 assert.equal((await fetch(base+'../firestore.rules')).status,404);
 }finally{child.kill();await new Promise(r=>child.once('exit',r))}
});
import {edgeAnchor,anchorPoint,bounds,applyLayout,makeLayout,validateLayout} from './public/geometry.js';
test('edge strings track image rotation and scale',()=>{const item={x:300,y:200,width:200,height:100,rotation:90};const anchor=edgeAnchor(item,{x:300,y:400});assert.ok(Math.abs(anchor.x-.5)<.00001);const point=anchorPoint(item,anchor);assert.ok(Math.abs(point.x-300)<.00001);assert.ok(Math.abs(point.y-300)<.00001);const scaled=anchorPoint({...item,width:400},anchor);assert.ok(Math.abs(scaled.y-400)<.00001);const box=bounds([item]);assert.ok(Math.abs(box.right-box.left-100)<.00001)});
test('layout preserves exact strings, clusters and hidden seed items',async()=>{const seed=JSON.parse(await readFile(new URL('./public/board.json',import.meta.url)));let board=applyLayout(mergeBoard(seed,[]),null);board.items=board.items.filter(i=>i.id!=='belief');board.clusters=[{id:'group',title:'AI',reason:'Shared context',members:['claude','hal']}];board.strings=[{id:'edge',from:'claude',to:'hal',a:{x:.5,y:0},b:{x:-.5,y:0}}];const layout=makeLayout(board,seed.items.map(i=>i.id));validateLayout(layout);const restored=applyLayout(mergeBoard(seed,[]),layout);assert.ok(!restored.items.some(i=>i.id==='belief'));assert.equal(restored.strings.length,1);assert.deepEqual(restored.strings[0].a,{x:.5,y:0});assert.equal(restored.clusters[0].reason,'Shared context');assert.throws(()=>validateLayout({...layout,transforms:{bad:{x:0,y:0,width:20,height:20,rotation:NaN}}}));const newBoard=applyLayout(mergeBoard(seed,[item]),layout);assert.ok(newBoard.strings.some(s=>s.from==='student'&&s.to==='hal'))});
import {fitScene,sceneSize} from './public/scene.js';
test('whole-board camera retains physical proportions and includes older layouts',()=>{const items=[{x:400,y:300,width:60,height:70}];const viewport={clientWidth:1500,clientHeight:800};const camera=fitScene(viewport,items);assert.ok(Math.abs(camera.tx+700*camera.scale-750)<.001);assert.ok(Math.abs(camera.ty+350*camera.scale-400)<.001);assert.deepEqual(sceneSize(items),{width:1400,height:700});assert.ok(sceneSize([{x:800,y:850,width:100,height:200}]).height>=950);const detail=fitScene(viewport,items,false);assert.ok(detail.scale>camera.scale)});
import {initializePins,addPin,connectPins,orderedStrings,localAnchor,pinPosition} from './public/pins.js';
test('real pins migrate legacy strings and preserve chronological layers across layout saves',async()=>{const seed=JSON.parse(await readFile(new URL('./public/board.json',import.meta.url)));const board=initializePins(applyLayout(mergeBoard(seed,[]),null));const existing=board.strings.length;const first=addPin(board,board.items[0],{x:.2,y:.1},'2026-10-10T14:00:00Z'),last=addPin(board,board.items[1],{x:-.2,y:.2},'2026-10-10T14:01:00Z');const string=connectPins(board,first,last,'2026-10-10T14:02:00Z');assert.equal(string.order,existing);assert.equal(string.createdAt,'2026-10-10T14:02:00Z');assert.throws(()=>connectPins(board,first,last));const layout=makeLayout(board,board.items.map(i=>i.id));validateLayout(layout);const restored=initializePins(applyLayout(mergeBoard(seed,[]),JSON.parse(JSON.stringify(layout))));assert.equal(orderedStrings(restored.strings).at(-1).id,string.id);assert.equal(restored.pins.find(p=>p.id===first.id).createdAt,'2026-10-10T14:00:00Z');initializePins(restored);assert.equal(restored.strings.length,existing+1);const before=pinPosition(board,first);board.items[0].x+=30;assert.ok(Math.abs(pinPosition(board,first).x-before.x-30)<.000001);const item={x:200,y:200,width:100,height:200,rotation:90};const anchor=localAnchor(item,{x:150,y:220});assert.ok(Math.abs(anchor.x-.2)<.0001);assert.ok(Math.abs(anchor.y-.25)<.0001)});
import {additionEvents,atAddition,splayBoard,fitSplay} from './public/explore.js';
test('timeline reverses known additions, retains undated baseline, and splay never edits saved positions',()=>{const board={items:[{id:'old',x:200,y:200,width:100,height:80},{id:'new',x:200,y:200,width:100,height:80,createdAt:{seconds:100}}],pins:[],strings:[{id:'line',from:'old',to:'new',createdAt:'1970-01-01T00:02:00Z'}],clusters:[],connections:[['old','new']]};const events=additionEvents(board);assert.equal(events.length,2);assert.equal(atAddition(board,events,0).items.length,1);assert.equal(atAddition(board,events,1).strings.length,0);assert.equal(atAddition(board,events,2).strings.length,1);const saved=JSON.stringify(board),splayed=splayBoard(board);assert.notEqual(splayed.items[0].x,splayed.items[1].x);assert.equal(JSON.stringify(board),saved);assert.equal(validateSubmission({...item,sourceUrl:'https://example.com',articleText:'An article'}).articleText,'An article');assert.throws(()=>validateSubmission({...item,sourceUrl:'javascript:alert(1)'}));assert.throws(()=>validateSubmission({...item,articleText:'x'.repeat(20001)}))});

test('splay fans around a fixed center, separates groups and frames the entire expanded spread',()=>{const board={items:[{id:'hub',x:700,y:350,width:100,height:100},{id:'a',x:850,y:350,width:200,height:160},{id:'b',x:850,y:350,width:200,height:160},{id:'c',x:450,y:180,width:120,height:120}],clusters:[]};const saved=JSON.stringify(board),spread=splayBoard(board);assert.equal(JSON.stringify(board),saved);assert.deepEqual(spread.items[0],board.items[0]);for(let a=0;a<spread.items.length;a++)for(let b=a+1;b<spread.items.length;b++){const x=spread.items[a],y=spread.items[b];assert.ok(Math.abs(x.x-y.x)>=(x.width+y.width)/2+59||Math.abs(x.y-y.y)>=(x.height+y.height)/2+59)}for(const viewport of [{clientWidth:1500,clientHeight:800},{clientWidth:390,clientHeight:694}]){const camera=fitSplay(viewport,spread.items);assert.ok(Math.abs(camera.tx+700*camera.scale-viewport.clientWidth/2)<.001);assert.ok(Math.abs(camera.ty+350*camera.scale-viewport.clientHeight/2)<.001);const box=bounds(spread.items);assert.ok(camera.tx+box.left*camera.scale>=0);assert.ok(camera.tx+box.right*camera.scale<=viewport.clientWidth);assert.ok(camera.ty+box.top*camera.scale>=0);assert.ok(camera.ty+box.bottom*camera.scale<=viewport.clientHeight)}const clustered=splayBoard({...board,clusters:[{members:['a','c']}]});const a=clustered.items.find(i=>i.id==='a'),c=clustered.items.find(i=>i.id==='c');assert.equal(a.x-c.x,400);assert.equal(a.y-c.y,170)});
